### PR TITLE
Feature: Highlight current indent level

### PR DESCRIPTION
**Pull request by sebmeister2077**
As mentioned in #3 .

I want to ask you @CodyPChristian how you would change the interface? 

Features:
-possibility to highlight the indent level and style it
-add indent level as a DOM attribute to allow for custom styling
-apply indent styling after window resizes

Fixes:
-fixed indent not taking into account the content and its styles (indents until content margin is 0 would be half as effective)

### CODE REVIEW

**Comment by CodyPChristian** [comment]
@sebmeister2077 nice work! Looks good to me :)

**Comment by sebmeister2077** [comment]
> @sebmeister2077 nice work! Looks good to me :) 

Will have another look later today and merge

**Comment by sebmeister2077** [comment]
@CodyPChristian  I still don't know what default color to use.  A grayish color? 🤔 What do you think?

**Comment by sebmeister2077** [comment]
I think i won't apply a default color. I will let the user decide for themselves. :D

**Comment by CodyPChristian** [comment]
@sebmeister2077 Either a gray or yellow? With an option to change it. If left empty or set false would disable the color?

**Comment by sebmeister2077** [comment]
> @sebmeister2077 Either a gray or yellow? With an option to change it. If left empty or set false would disable the color?

Unless there are already other editors out there with a generic example I wouldn't add a default color.
Eitherway the users would want to apply their own color palette.

I will add usage about this feature in the ReadMe so it should be okay

**Comment by CodyPChristian** [comment]
@sebmeister2077  Used latest version in production and everything worked great! Thanks!

**Pull request merged**
